version: '3'
services:
  spark-app:
    build: .
    image: andmalwer:latest
    container_name: andmalwer
    environment:
        - SPARK_MASTER_NAME=spark-master
        - SPARK_MASTER_PORT=7077
        - SPARK_APPLICATION_ARGS=packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.4
        - SPARK_APPLICATION_PYTHON_LOCATION=/app/app.py
        - MALWER_DATA=hdfs://namenode:9000/data/hadoopspark/*.csv
        - ENABLE_INIT_DAEMON=false
    links:
        - spark-master
        
  namenode:
    build: ./hdfs
    image: hdfsnamenode
    container_name: namenode
    environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        - CLUSTER_NAME=hadooptest
    ports:
        - "9870:9870"
        - "9000:9000"
    volumes:
    - D:/PROJECTS/hadoopspark:/opt/hadoopspark
    
  datanode:
        build: ./hdfs/datanode
        image: hdfsdatanode
        container_name: datanode
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        volumes:
            - D:/PROJECTS/hadoopspark:/opt/hadoopspark
    

    
      
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"